### ISSUE TITLE
Delete ROLLBACK_COMPLETE CloudFormation stack

### ISSUE THREAD

**Issue by JoeShi** [aws-solutions/centralized-logging-with-opensearch#130]
### Describe the feature

The CLO console will provision CloudFormation stack, however, it will NOT delete the stack which is in ROLLBACK_COMPLETE status.

### Use Case

Remove the ROLLBACK_COMPLETE CloudFormation stacks, and keep the list clear.

### Solution version used

v1.0.1

**Comment by qmugnier** [comment]
I think it is better not to delete the stack so you can investigate the issue afterwards.
Actually, an option to keep the objects instead of rollback would make sense. I have tons of iam issues with the app. If I can fix the issue, or better, the root cause and restart from the failure point, I am more efficient.

Would it be possible to add the option: keep the objects if failed?

**Comment by JoeShi** [comment]
Thanks for reaching. @qmugnier Currently, the solution will not delete sub stacks provisioned through the console. You can view the error in the CloudFormation console. Do you mean you want to keep the objects provisioned by CloudFormation even if the entire stack was failed?

**Comment by qmugnier** [comment]
@JoeShi : Well, it would be convenient to be able to keep the objects, as an IAM error for the generated objects is easy to fix, so if you delete the stack you cannot really solve the issue as the involved role or policy is gone.
